### ISSUE TITLE
Decide what to do about mdg mobile-packages

### ISSUE THREAD

**Issue by hwillson** [meteor/mobile-packages#134]
Migrating this over from https://github.com/meteor/meteor/issues/6041.

----

(originally reported by @martijnwalraven)

We should decide whether there is any value in maintaining `mdg:camera`, `mdg:geolocation` and `mdg:reload-on-resume` in https://github.com/meteor/mobile-packages, or whether it would make more sense to deprecate them.

**Comment by skirunman** [comment]
I would vote to put each in their own MDG repository and then allow some community maintenance. I believe there is value in some maintenance of these packages as they are mostly Meteor wrappers for standard Cordova plugins and have pretty high usage. I'd be willing to spend a bit of time on helping with `mdg:geolocation`.

Would be great to get this done now as there are some low hanging fruit in open pull requests.

**Comment by StorytellerCZ** [comment]
The plan is that currently the packages will stay where they are. I'm cleaning the issue right now (mostly closing them due to age to get a clean slate). Also I'm tackling all the low hanging fruit like updating the examples and easy patches. Once all of that is done we'll look into getting these packages some more love.
