### ISSUE TITLE
Reload.isWaitingForResume() - ReferenceError: Reload is not defined

### ISSUE THREAD

**Issue by solo999** [meteor/mobile-packages#16]
Reload.isWaitingForResume() - ReferenceError: Reload is not defined
Seems like Reload was not exported to global namespace...

**Comment by txs** [comment]
it's still undefined thanks!

**Comment by solo999** [comment]
It was fixed for me in 1.0.4

**Comment by txs** [comment]
Can I call it in desktop?  Or I can only  view  in mobile?  How do I know if it's working?

**Comment by stubailo** [comment]
On desktop or mobile web, this won't do anything because the page will always reload immediately. On Cordova, adding the `mdg:reload-on-resume` package will make the app not refresh immediately, but rather wait until the app is closed and resumed. When a new version of the app has been downloaded but the page has not yet been refreshed with the new code, `Reload.isWaitingForResume()` will return true.

**Comment by txs** [comment]
Thanks I'll use a helper and test it :)
