### ISSUE TITLE
[FR] Add ability to reload without restarting app

### ISSUE THREAD

**Issue by lorensr** [meteor/mobile-packages#26]
`Can be used to display a message to the user that says "new version available, restart the app to update."`

It would be nice to be able to display a message, "New version available, click here to update", and then the in-app browser refreshes to the new version, especially since many users don't know how to restart apps. Could a `Reload.update()` function be added?

**Comment by boustanihani** [comment]
Is there a meteor package similar to https://atmospherejs.com/mdg/reload-on-resume but **for desktop clients**? I mean a package that changes the behavior of Meteor's hot code push feature and allows us to attache custom code and define what happens when a new version is downloaded or detected. 

I think doing a full page reload (for example by calling ```window.location.reload()```) eliminates the risk of getting some invalid app state and the need to manually reset any variables or components. IMO it is not a big deal if a user needs to refill some form when this happens.

**Comment by stubailo** [comment]
The way hot code push is implemented currently actually does do a full page reload for exactly this reason. You can attach hooks to reload related events via the `reload` package, but I don't think the API is well documented. Look at the source code of this package for an example of how to use it.

**Comment by boustanihani** [comment]
@stubailo Thanks, good to know :)

You mean I should take a look at this package ? =>
https://github.com/meteor/meteor/tree/devel/packages/reload

**Comment by stubailo** [comment]
That would also be helpful, but I meant the `mdg:reload-on-resume` package, since it uses the `reload` API.

**Comment by boustanihani** [comment]
Okay :) I'll take a look.. THX

**Comment by sasikanth513** [comment]
@stubailo @Slava 
 If we use `window.location.reload()` connection to the server is lost and we are getting 

` Server sent add for existing id: 5JHx7YWauQobBXC7H` error

Is there any smooth way to do this like `Reload.update()`?

My code
```
function initializeUpdate(){
      document.addEventListener('resume', function(){
        if(Reload.isWaitingForResume()){
          window.location.reload();
        }
      }, false);
  }
  document.addEventListener("deviceready", initializeUpdate, false);
```

**Comment by sasikanth513** [comment]
This is more of `grounddb` issue I think 
https://github.com/GroundMeteor/db/issues/22

**Comment by mitiaptest** [comment]
+1
