### ISSUE TITLE
GeoLocation and Camera not working on `meteor run ios`

### ISSUE THREAD

**Issue by ghost** [meteor/mobile-packages#97]
I downloaded the repo and ran the three example apps without changing any of the code. They all work in Chrome but none of them work in iOS simulator. Neither GeoLocation or Camera works, though it did prompt me to give location permission (which I allowed). Below are some screenshots. Can anyone help me get it working? Thanks!

![screen shot 2015-12-23 at 1 44 57 pm](https://cloud.githubusercontent.com/assets/1624873/11972225/eeadbc86-a97b-11e5-9b56-8b8585cc1f12.png)

![screen shot 2015-12-23 at 1 42 45 pm](https://cloud.githubusercontent.com/assets/1624873/11972222/dc8d922e-a97b-11e5-87c3-5022bc3a0be6.png)

**Comment by sasikanth513** [comment]
Is this because of this https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

I have same issues in android, If I run my app in browser I'm able to get lat and lng values,

If I run the same app i android device I'm not getting any lat, lng values.

following line is from  above link
### localhost is treated as a secure origin over HTTP, so if you're able to run your server from localhost, you should be able to test the feature on that server.

as meteor mobile apps runs with `meteor.local` origin, Is that the issue? If it is how to fix this?

**Comment by sasikanth513** [comment]
@artitw did you find any solution for this?

**Comment by artitw** [comment]
@sasikanth513 - Maybe the iOS simulator is buggy. I have not yet run it on an actual iOS device, but for whatever reason, the app deploys fine when I create the apk and run it on an actual Android device. I've settled with this solution for the time being. Hope it helps.

**Comment by sasikanth513** [comment]
@artitw thanks for the reply, appreciate it. I know it will work fine if I deploy but I need to test the feature before deploying.

**Comment by sasikanth513** [comment]
UPDATE: even after deploying and pointing my server to https it is not working

**Comment by StorytellerCZ** [comment]
Closing this issue due to age.
